services:
  postgres:
    image: postgres:15-alpine
    container_name: subscription_postgres
    environment:
      POSTGRES_DB: subscription_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d subscription_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: subscription_app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/subscription_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL-AUTO: update

volumes:
  postgres_data: